[package]
name = "node-meminfo"
version = "2.0.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/node-int32"
homepage = "https://magiclen.org/node-js-int32/"
keywords = ["node.js", "meminfo"]
categories = []
description = "Get memory information on Linux."
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
scanner-rust = "2"

[dependencies.neon]
version = "0.8"
default-features = false
features = ["napi-6"]
